# Generated by Django 5.2.3 on 2025-07-17 12:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fieldsubmission",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Field Submission",
                "verbose_name_plural": "Field Submissions",
            },
        ),
        migrations.AddField(
            model_name="fieldsubmission",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fieldsubmission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="fieldsubmission",
            name="kml_file",
            field=models.FileField(blank=True, null=True, upload_to="kml_files/"),
        ),
        migrations.AlterField(
            model_name="fieldsubmission",
            name="polygon",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fieldsubmission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
