# Generated by Django 5.2.3 on 2025-07-17 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_alter_fieldsubmission_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="fieldsubmission",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fieldsubmission",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_fields",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
